#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
issues:
  exclude-rules:
    - path: _test\.go
      linters:
      - dupl
      - goconst
linters:
  enable:
    - golint
    - govet
    - errcheck 
    - staticcheck 
    - unused 
    - gosimple 
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - gofmt 
    - goimports
    - misspell 
    - unparam 
    - whitespace
    - unconvert
    - goconst 
    - prealloc
    - nakedret
    - dogsled
    
linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
    